name: Publish Extension

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: node_modules/vsce/out/vsce publish -p $VSCE_TOKEN
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

