name: Prepare for publishing

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - name: Publish package to marketplace
      if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
      run: node_modules/vsce/out/vsce publish -p $VSCE_TOKEN
      env:
        VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

