name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v2.1.3

jobs:
  release:
    name: Publish github release / marketplace
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: Parse semver string
        id: semver_parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref }}
          version_extractor_regex: '\/v(.*)$'
      - name: Use parsed semver
        run: |
            echo "v${{ steps.semver_parser.outputs.fullversion }}"

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: clean install dependencies
        run: npm ci

      - name: update metadata in package.json
        uses: onlyutkarsh/patch-files-action@v1.0.1
        with:
          files: '${{github.workspace}}/package.json'
          patch-syntax: |
            = /version => "${{ steps.semver_parser.outputs.fullversion }}"

      - name: compile and create vsix
        run: npm run package

      - name: upload vsix as artifact
        uses: actions/upload-artifact@v1
        with:
          name: asciidoctor-vscode-${{steps.gitversion.outputs.semVer}}.vsix
          path: ${{github.workspace}}/asciidoctor-vscode-${{steps.gitversion.outputs.semVer}}.vsix

      # # package and publish to marketplace
      # - name: Publish package to marketplace
      #   run: node_modules/vsce/out/vsce publish -p $VSCE_TOKEN
      #   env:
      #     VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

